package com.example.bigbillionadmin.helper;

public class Constant {
    //public static final String MainBaseUrl = "http://app.bigbillionenterprises.co.in/";
    //public static final String MainBaseUrl = "http://192.168.43.38/bigbillion/";
    public static final String MainBaseUrl = "https://bigbillion.graymatterworks.com/";

    public static final String BaseUrl = MainBaseUrl + "api/";
    public static final String POINTS_LIST_URL = BaseUrl + "pointslist.php";
    public static final String UPDATE_POINTS_URL = BaseUrl + "updatepoints.php";
    public static final String UPDATE_SETTINGS_URL = BaseUrl + "update_settings.php";
    public static final String SETTINGS_URL = BaseUrl + "settings.php";
    public static final String MANAGE_WALLET_URL = BaseUrl + "managewallet.php";
    public static final String UPDATE_WITHDRAWALS_URL = BaseUrl + "updatewithdrawals.php";
    public static final String WITHDRAWAL_LISTS_URL = BaseUrl + "allwithdrawalslist.php";
    public static final String POST_RESULTS_URL = BaseUrl + "postresults.php";
    public static final String ALL_RESULT_URL = BaseUrl + "all_result.php";
    public static final String RESULT_LIST_URL = BaseUrl + "resultlist.php";
    public static final String ADD_RESULT_URL = BaseUrl + "add_result.php";
    public static final String DELETE_RESULT_URL = BaseUrl + "delete_result.php";
    public static final String ADMIN_LOGIN_URL = BaseUrl + "adminlogin.php";
    public static final String SHARED_POINTS_LIST_URL = BaseUrl + "sharepointlists.php";
    public static final String USERS_LIST_URL = BaseUrl + "userslist.php";
    public static final String UPDATE_USERS_ADMIN_URL = BaseUrl + "update_user_admin.php";
    public static final String WINNER_LIST_URL = BaseUrl + "winnerlist.php";
    public static final String BIDS_USER_URL = BaseUrl + "bidsuserlist.php";
    public static final String ALL_BIDS_URL = BaseUrl + "allbids.php";
    public static final String USER_BLOCK_URL = BaseUrl + "user_block.php";
    public static final String DELETE_BIDS_URL = BaseUrl + "deletebid.php";
    public static final String SEARCH_USER_URL = BaseUrl + "searchuser.php";
    public static final String BIDSLIST_URL = BaseUrl + "bidslist.php";
    public static final String HARUFBIDSLIST_URL = BaseUrl + "harufbidslist.php";
    public static final String ALLHARUFBIDSLIST_URL = BaseUrl + "allharufbids.php";
    public static final String COUNTBIDSLIST_URL = BaseUrl + "allbids_count.php";
    public static final String MOBILE = "mobile";
    public static final String POINT_ID = "point_id";
    public static final String DATE = "date";
    public static final String TYPE = "type";
    public static final String WITHDRAWAL_ID = "withdrawal_id";
    public static final String STATUS = "status";
    public static final String WHATSAPP_NUM = "whatspp_number";
    public static final String YOUTUBE_LINK = "youtube_link";
    public static final String UPI = "upi";
    public static final String NEWSINFO = "newsinfo";
    public static final String USER_ID = "user_id";
    public static final String USER_STATUS = "user_status";
    public static final String PASSWORD = "password";
    public static final String SEARCH = "search";
    public static final String AMOUNT = "amount";
    public static final String MONTH = "month";
    public static final String TRANSLISTS_URL = BaseUrl + "translists.php";
    public static final String YEAR = "year";
    public static final String GAME_NAME = "game_name";
    public static final String GAME_TYPE = "game_type";

    public static final String DS = "DS";
    public static final String GB = "GB";
    public static final String GL = "GL";
    public static final String FD = "FD";
    public static final String DAY = "day";
    public static final String GAME_DATE = "game_date";
    public static final String GAME_METHOD = "game_method";
    public static final String NUMBER = "number";
    public static final String POINTS = "points";
    public static final String REASON = "reason";
    public static final String TOTAL_POINTS = "total_points";
    public static final String Login = "login";
    public static final String ID = "id";
    public static final String NAME = "name";
    public static final String EARN = "earn";
    public static final String SUCCESS = "success";
    public static final String TOTALUSERS = "total_users";
    public static final String JODI = "jodi";
    public static final String ODDEVEN = "odd_even";
    public static final String QUICKCROSS= "quick_cross";
    public static final String HARUF = "haruf";
    public static final String RESULT = "result";
    public static final String MESSAGE = "message";
    public static final String DATA = "data";
    public static final String ACCOUNT_NO = "account_number";
    public static final String IFSC_CODE = "ifsc_code";
    public static final String HOLDER_NAME = "holder_name";
    public static final String GPAY = "gpay";
    public static final String PAYTM = "paytm";
    public static final String PHONEPE = "phonepe";


    public static final String MIN_DEPOSIT = "min_deposit";

    public static final String MIN_WITHDRAWAL = "min_withdrawal";
    public static final String MAX_WITHDRAWAL = "max_withdrawal";
}